apiVersion: v1
kind: Pod
metadata:
  labels:
    app: scout
  name: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
    ports:
    - containerPort: 80