apiVersion: v1
kind: Service
metadata:
  name: tempo-4318-nodeport
spec:
  ports:
  - nodePort: 30002
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app.kubernetes.io/name: tempo
  sessionAffinity: None
  type: NodePort