kind: PersistentVolume
apiVersion: v1
metadata:
  name: myvolume
spec:
  storageClassName: standard
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/test
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: test-pvc
      mountPath: /test
  volumes:
  - name: test-pvc
    hostPath:
     path: /tmp/test
     type: Directory
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}