apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: test-secret
  - name: cm-volume
    configMap:
      name: test-cm
  - name: test-cm-file
    configMap:
      name: test-cm-file
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: secret-volume
      mountPath: /test/
    - name: cm-volume
      mountPath: /test1/
    - name: test-cm-file
      mountPath: /test2/test1.properties
      subPath: test1.properties
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: user
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: pass
    - name: CM-VALUE
      valueFrom:
        configMapKeyRef:
          name: test-cm
          key: value1
    