apiVersion: v2
dependencies:
- condition: keycloak.enabled
  name: keycloak
  repository: https://charts.bitnami.com/bitnami
  version: 12.3.0
description: Identity Helm Chart for Kubernetes
icon: https://helm.camunda.io/imgs/camunda.svg
name: identity
type: application
version: 8.2.13
