apiVersion: v1
kind: Pod
metadata:
  name: probe
  labels: 
    app: probe
spec:
  containers:
    - name: probe
      image: josepht96/probe:latest
      imagePullPolicy: Always
      env: 
      - name: URL
        value: "http://nginx:8080"
      - name: INTERVAL
        value: "5"