apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  labels: 
    app: keycloak
spec:
  containers:
    - name: keycloak
      image: quay.io/keycloak/keycloak:latest
      ports:
      - containerPort: 8080
      - containerPort: 8443
      args: ["start-dev"]
      env:
      - name: KEYCLOAK_ADMIN
        value: admin
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: password123
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  ports:
  - name: tcp
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: keycloak
  type: NodePort