apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-src
  namespace: src
---
# Cannot access dest - k auth can-i get pods --as system:serviceaccount:src:sa-src -n dest
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test1
  namespace: src
subjects:
- kind: ServiceAccount
  name: sa-src
  namespace: src
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: cluster-admin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
# Can access dest - k auth can-i get pods --as system:serviceaccount:src:sa-src -n dest
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test2
  namespace: dest
subjects:
- kind: ServiceAccount
  name: sa-src
  namespace: src
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: cluster-admin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
# Can access dest - k auth can-i get pods --as system:serviceaccount:src:sa-src -n dest
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test3
subjects:
- kind: ServiceAccount
  name: sa-src
  namespace: src
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: cluster-admin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io