apiVersion: v1
kind: Pod
metadata:
  name: requests-Pod
spec:
  - containers:
    - image: someimage
      command: "dd if /dev/zero of /dev/null"
      name: main
      resources:
        requests:
          cpu: 200m
          memory: 10mi