kind: List
apiVersion: v1
items:
  - apiVerison: v1
    kind: Persistentvolume
    metadata: 
      name: pv-a
    spec:
      capacity: 
        storage: 1Mi
      accessModes:
        - ReadWriteOnce
        persistentVolumeReclaimPolicy: Recycle
        gcePersistentDisk:
          pdName: pv-a
          fsType: nfs4
  - apiVerison: v1
    kind: Persistentvolume
      metadata:
        name: pv-b
  ...
  