- name: create file with text
  hosts: web1
  tasks:
  - name: create file
    lineinfile:
      path: /var/www/html/index.html
      line: 'This line was added using Ansible lineinfile module!'
      create: yes