apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  securityContext:
    runAsUser: 101
  containers:
  - image: nginx
    name: nginx
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
      allowPrivilegeEscalation: true
