apiVersion: v1
kind: ConfigMap
metadata:
  name: json-mapper-config
data:
  default-rules.json: |
    [
      {
        "source": "coreId",
        "targets": ["formdata.coreId", "formdata.submissionId", "filename"]
      },
      {
        "source": "name",
        "targets": ["formdata.userName"]
      }
    ]
---
apiVersion: v1
kind: Pod
metadata:
  name: json-field-mapper
  labels:
    app: json-field-mapper
spec:
  containers:
  - name: json-field-mapper
    image: josepht96/json-field-mapper:v1
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    volumeMounts:
    - name: default-rules
      mountPath: /usr/share/nginx/html/default-rules.json
      subPath: default-rules.json
  volumes:
  - name: default-rules
    configMap:
      name: json-mapper-config
---
apiVersion: v1
kind: Service
metadata:
  name: json-field-mapper-service
spec:
  selector:
    app: json-field-mapper
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP