apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: zeebe-ra
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: zeebe-gateway
  jwtRules:
  - issuer: "http://camunda-keycloak/auth/realms/camunda-platform"
    # jwksUri: "http://camunda-keycloak/auth/realms/camunda-platform/protocol/openid-connect/certs"
    forwardOriginalToken: true
    jwks: |
      {"keys":[{"kid":"qAOWuNJG9AZBQUHVyvcPayMYoZ5f0-USTlhMTfT-3cs","kty":"RSA","alg":"RS256","use":"enc","n":"hoySqDuMTnFsPp4_GDKfkwh853S97pRjMSKCKBTQ6dLnz-yK81xOeivEjfMlFC5KIX8yT2-iFVkYcLHwN1emdN5Bsdcrb3F_Ff7AqMSNociJmAtKb70dLVjG_xSGUZjlSrHq4DGsSYajGKs8qY4Qn2RBNTWntW_YNpqi6DBBIW816Tmv39xthkeKnBn8N6K-2h2mkSMx_N41C8AO0qYgLlh24ZBLiAvPU8XMP-ou5pPRW1Ge0OzwAfX5wq86uUpEGtHz16UBT3WyelZJxm1dt_Ofn8ngeZ6PmpqfBX9wQB5yFgKtJqX-NB3unvdzS-uydn1VoJw6Rl6dPp78CXu6RQ","e":"AQAB","x5c":["MIICrzCCAZcCBgGGg7KYJjANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQDDBBjYW11bmRhLXBsYXRmb3JtMB4XDTIzMDIyNDEzNTEwNVoXDTMzMDIyNDEzNTI0NVowGzEZMBcGA1UEAwwQY2FtdW5kYS1wbGF0Zm9ybTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAIaMkqg7jE5xbD6ePxgyn5MIfOd0ve6UYzEigigU0OnS58/sivNcTnorxI3zJRQuSiF/Mk9vohVZGHCx8DdXpnTeQbHXK29xfxX+wKjEjaHIiZgLSm+9HS1Yxv8UhlGY5Uqx6uAxrEmGoxirPKmOEJ9kQTU1p7Vv2DaaougwQSFvNek5r9/cbYZHipwZ/DeivtodppEjMfzeNQvADtKmIC5YduGQS4gLz1PFzD/qLuaT0VtRntDs8AH1+cKvOrlKRBrR89elAU91snpWScZtXbfzn5/J4Hmej5qanwV/cEAechYCrSal/jQd7p73c0vrsnZ9VaCcOkZenT6e/Al7ukUCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEANaUayMi02N6NbBMTcWnR3e02CJlpxIreiDC3o6aO8TIJmXQLqu7z8Uil77T4CZtxBxr2Sx6U0RDSkPUlLur9z+ID2x4M93zXbVDLaFAHff2LMcomzXbyRFYLVO7190rJ4xVle/eYu/9+9I7wXnMEAwhj0eVz3hT7eDKwu6ICiu9Hs9CnunugCiugFIA31KyaXdxVrFAW6mnptEOeXJ5BPaiw8XQtugzjVH2vPen9So+pJKfEo9Ln3h9e8tDQ8O4CX7YBRSmKc5/CUaQdSdvWnYMgmsI6zOsC4P0KW/BX+CJvEfxaq0DCJu9ihJBJeM+WS+c1KRKtcJlyKFEQzgbfpA=="],"x5t":"nrS23tWzbQpMNLy0u3p0WqqGkiQ","x5t#S256":"6S4gYKdEFkJ6E-Ux_IEbHdddjR6Puia5wCTjacMTn_8"},{"kid":"BfOgpeHvPgnSvD-w8dqtmRByBlcLgcqYprwCfFf_OQM","kty":"RSA","alg":"RS256","use":"sig","n":"idczkEppbx35gRephfm8lDgSafPNE3Ngw7YOeGPTRemTslIuILm0PoV7Kw8gJFle29O56d_SkbqnJ9pvKrFmovyHiQSTtOc3UNkmi4brEHyAtZYxYE01SA1ybJmjsfPOZdURkBGJdAjhapun5Q9YfoaJibY1jXXHAwSLwHtE8lkGUPMd93gT1JOzQ-XZgSPmvj03h6WxYuQSvulYjezTsekKkZ3ZRWouWfWfUXU4ivG79LrjR3ctys5gSAZWF9R9iW7X57hriKItNwzTQcouv1yy6RgIwmZeJxS19UtjFTZqfu886jzzUfpTDRGB3OT_bn0am_OFt0q9QCpuW44SPQ","e":"AQAB","x5c":["MIICrzCCAZcCBgGGg7KYTzANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQDDBBjYW11bmRhLXBsYXRmb3JtMB4XDTIzMDIyNDEzNTEwNVoXDTMzMDIyNDEzNTI0NVowGzEZMBcGA1UEAwwQY2FtdW5kYS1wbGF0Zm9ybTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAInXM5BKaW8d+YEXqYX5vJQ4EmnzzRNzYMO2Dnhj00Xpk7JSLiC5tD6FeysPICRZXtvTuenf0pG6pyfabyqxZqL8h4kEk7TnN1DZJouG6xB8gLWWMWBNNUgNcmyZo7HzzmXVEZARiXQI4Wqbp+UPWH6GiYm2NY11xwMEi8B7RPJZBlDzHfd4E9STs0Pl2YEj5r49N4elsWLkEr7pWI3s07HpCpGd2UVqLln1n1F1OIrxu/S640d3LcrOYEgGVhfUfYlu1+e4a4iiLTcM00HKLr9csukYCMJmXicUtfVLYxU2an7vPOo881H6Uw0Rgdzk/259GpvzhbdKvUAqbluOEj0CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAMJBHPpF115Duit10qj3carTW35mz56S+3AhyV2kCPBWsJq5E/MGtp01aASm6BIHIHQzRloYW/wQDnehI1shGP4LoZzFSgfdarKkBA0SeOaWEHzLQmE7XThQeEj6itlFak4LDIGZdFeFn9BPwEP/FVLHpZMrgnoeuJbzVfwGCjtYDYPMqQrmW5D/JHwdHpi6mOy+cAv3+0spmwswPBbcC3fOxTU2AQJ1dj6Pw8HyFAYZBkbVOZtRE3SuTmmZzaEVU0/b4l53HTQHEcbA2yxoRy6gvM3ctzZSP45WS6ez1sRrPDloxIBmOCo9eRMvxXSxKUjZx2W4IE6vlHN3MqucS2A=="],"x5t":"PoLNbDAcASC4YuDI8Gck1PjaHn0","x5t#S256":"qcrFFkyB1sD5-nRdslb-X1jfMftUtHaGc25NMI6xpZk"}]}
  - issuer: "http://camunda-keycloak.camunda.svc.cluster.local/auth/realms/camunda-platform"
    jwksUri: "http://camunda-keycloak/auth/realms/camunda-platform/protocol/openid-connect/certs"
    forwardOriginalToken: true
    # jwks: |
    #   {"keys":[{"kid":"qAOWuNJG9AZBQUHVyvcPayMYoZ5f0-USTlhMTfT-3cs","kty":"RSA","alg":"RS256","use":"enc","n":"hoySqDuMTnFsPp4_GDKfkwh853S97pRjMSKCKBTQ6dLnz-yK81xOeivEjfMlFC5KIX8yT2-iFVkYcLHwN1emdN5Bsdcrb3F_Ff7AqMSNociJmAtKb70dLVjG_xSGUZjlSrHq4DGsSYajGKs8qY4Qn2RBNTWntW_YNpqi6DBBIW816Tmv39xthkeKnBn8N6K-2h2mkSMx_N41C8AO0qYgLlh24ZBLiAvPU8XMP-ou5pPRW1Ge0OzwAfX5wq86uUpEGtHz16UBT3WyelZJxm1dt_Ofn8ngeZ6PmpqfBX9wQB5yFgKtJqX-NB3unvdzS-uydn1VoJw6Rl6dPp78CXu6RQ","e":"AQAB","x5c":["MIICrzCCAZcCBgGGg7KYJjANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQDDBBjYW11bmRhLXBsYXRmb3JtMB4XDTIzMDIyNDEzNTEwNVoXDTMzMDIyNDEzNTI0NVowGzEZMBcGA1UEAwwQY2FtdW5kYS1wbGF0Zm9ybTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAIaMkqg7jE5xbD6ePxgyn5MIfOd0ve6UYzEigigU0OnS58/sivNcTnorxI3zJRQuSiF/Mk9vohVZGHCx8DdXpnTeQbHXK29xfxX+wKjEjaHIiZgLSm+9HS1Yxv8UhlGY5Uqx6uAxrEmGoxirPKmOEJ9kQTU1p7Vv2DaaougwQSFvNek5r9/cbYZHipwZ/DeivtodppEjMfzeNQvADtKmIC5YduGQS4gLz1PFzD/qLuaT0VtRntDs8AH1+cKvOrlKRBrR89elAU91snpWScZtXbfzn5/J4Hmej5qanwV/cEAechYCrSal/jQd7p73c0vrsnZ9VaCcOkZenT6e/Al7ukUCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEANaUayMi02N6NbBMTcWnR3e02CJlpxIreiDC3o6aO8TIJmXQLqu7z8Uil77T4CZtxBxr2Sx6U0RDSkPUlLur9z+ID2x4M93zXbVDLaFAHff2LMcomzXbyRFYLVO7190rJ4xVle/eYu/9+9I7wXnMEAwhj0eVz3hT7eDKwu6ICiu9Hs9CnunugCiugFIA31KyaXdxVrFAW6mnptEOeXJ5BPaiw8XQtugzjVH2vPen9So+pJKfEo9Ln3h9e8tDQ8O4CX7YBRSmKc5/CUaQdSdvWnYMgmsI6zOsC4P0KW/BX+CJvEfxaq0DCJu9ihJBJeM+WS+c1KRKtcJlyKFEQzgbfpA=="],"x5t":"nrS23tWzbQpMNLy0u3p0WqqGkiQ","x5t#S256":"6S4gYKdEFkJ6E-Ux_IEbHdddjR6Puia5wCTjacMTn_8"},{"kid":"BfOgpeHvPgnSvD-w8dqtmRByBlcLgcqYprwCfFf_OQM","kty":"RSA","alg":"RS256","use":"sig","n":"idczkEppbx35gRephfm8lDgSafPNE3Ngw7YOeGPTRemTslIuILm0PoV7Kw8gJFle29O56d_SkbqnJ9pvKrFmovyHiQSTtOc3UNkmi4brEHyAtZYxYE01SA1ybJmjsfPOZdURkBGJdAjhapun5Q9YfoaJibY1jXXHAwSLwHtE8lkGUPMd93gT1JOzQ-XZgSPmvj03h6WxYuQSvulYjezTsekKkZ3ZRWouWfWfUXU4ivG79LrjR3ctys5gSAZWF9R9iW7X57hriKItNwzTQcouv1yy6RgIwmZeJxS19UtjFTZqfu886jzzUfpTDRGB3OT_bn0am_OFt0q9QCpuW44SPQ","e":"AQAB","x5c":["MIICrzCCAZcCBgGGg7KYTzANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQDDBBjYW11bmRhLXBsYXRmb3JtMB4XDTIzMDIyNDEzNTEwNVoXDTMzMDIyNDEzNTI0NVowGzEZMBcGA1UEAwwQY2FtdW5kYS1wbGF0Zm9ybTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAInXM5BKaW8d+YEXqYX5vJQ4EmnzzRNzYMO2Dnhj00Xpk7JSLiC5tD6FeysPICRZXtvTuenf0pG6pyfabyqxZqL8h4kEk7TnN1DZJouG6xB8gLWWMWBNNUgNcmyZo7HzzmXVEZARiXQI4Wqbp+UPWH6GiYm2NY11xwMEi8B7RPJZBlDzHfd4E9STs0Pl2YEj5r49N4elsWLkEr7pWI3s07HpCpGd2UVqLln1n1F1OIrxu/S640d3LcrOYEgGVhfUfYlu1+e4a4iiLTcM00HKLr9csukYCMJmXicUtfVLYxU2an7vPOo881H6Uw0Rgdzk/259GpvzhbdKvUAqbluOEj0CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAMJBHPpF115Duit10qj3carTW35mz56S+3AhyV2kCPBWsJq5E/MGtp01aASm6BIHIHQzRloYW/wQDnehI1shGP4LoZzFSgfdarKkBA0SeOaWEHzLQmE7XThQeEj6itlFak4LDIGZdFeFn9BPwEP/FVLHpZMrgnoeuJbzVfwGCjtYDYPMqQrmW5D/JHwdHpi6mOy+cAv3+0spmwswPBbcC3fOxTU2AQJ1dj6Pw8HyFAYZBkbVOZtRE3SuTmmZzaEVU0/b4l53HTQHEcbA2yxoRy6gvM3ctzZSP45WS6ez1sRrPDloxIBmOCo9eRMvxXSxKUjZx2W4IE6vlHN3MqucS2A=="],"x5t":"PoLNbDAcASC4YuDI8Gck1PjaHn0","x5t#S256":"qcrFFkyB1sD5-nRdslb-X1jfMftUtHaGc25NMI6xpZk"}]}

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: zeebe-ap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: zeebe-gateway
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
    # - source:
    #     namespaces: ["camunda"]
---

# kind: AuthorizationPolicy
# apiVersion: security.istio.io/v1beta1
# metadata:
#   name: zeebe-ap-deny-all
#   namespace: camunda
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/component: zeebe-gateway
#   action: DENY
#   rules:
#     - from:
#         - source:
#             # if validation fails, principal will be empty, so it wont match "*"
#             notRequestPrincipals: ["*"]
#       to:
#         - operation:
#             hosts: 
#             - camunda-zeebe-gateway
#             - camunda-zeebe-gateway.camunda.svc.cluster.local
#             ports:
#             - "26500"
#             - "9200"
# ---

# kind: AuthorizationPolicy
# apiVersion: security.istio.io/v1beta1
# metadata:
#   name: ext-authz-oauth2-allow
#   namespace: camunda
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/component: zeebe-gateway
#   action: ALLOW
#   rules:
#   - from:
#       - source:
#           requestPrincipals: ["*"]
#     to:
#       - operation:
#           hosts: ["camunda-zeebe-gateway:26500"]
#           notPaths: ["/auth/*","/identity/*"]
# ---