apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: zeebe-ra
spec:
  selector:
    matchLabels:
      app: zeebe
  jwtRules:
  - issuer: "http://keycloak.default.svc.cluster.local:8080/realms/master"
    jwksUri: "http://keycloak.default.svc.cluster.local:8080/realms/master/protocol/openid-connect/certs"

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: zeebe-ap
spec:
  selector:
    matchLabels:
      app: zeebe
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]