apiVersion: v1
kind: Pod
metadata:
  name: zeebe-worker
spec:
  restartPolicy: Always
  containers:
  - name: zeebe-worker
    image: josepht96/zeebe-worker:latest
    imagePullPolicy: Always
    resources: {}
    env:
    - name: ZEEBE_ADDRESS
      value: "zeebe.camunda.svc.cluster.local:26500"
    - name: ZEEBE_HOST
      value: "zeebe.camunda.svc.cluster.local"
    - name: ZEEBE_PORT
      value: "26500"
    - name: ZEEBE_CLIENT_ID
      value: "test-auth"
    - name: ZEEBE_CLIENT_SECRET
      value: "d6apt9pQkI6666bC17YiH3Jjp8mBEy6w"
    - name: ZEEBE_AUTHORIZATION_SERVER_URL
      value: "http://keycloak.default.svc.cluster.local:8080/realms/master/protocol/openid-connect/token"