apiVersion: v1
kind: Pod
metadata:
<<<<<<< HEAD
  name: nginx
=======
  name: zeebe-worker
  annotations:
    istio: test
>>>>>>> 3fcf752a91ec3d1b649c0f5607af3e8764267e13
spec:
  # volumes:
  #   - name: kubernetes-storage
  #     persistentVolumeClaim:
  #       claimName: k8s-pvc
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      resources: {}
      # volumeMounts:
      #   - mountPath: "/tmp/"
      #     name: kubernetes-storage
