apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  # volumes:
  #   - name: kubernetes-storage
  #     persistentVolumeClaim:
  #       claimName: k8s-pvc
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      resources: {}
      # volumeMounts:
      #   - mountPath: "/tmp/"
      #     name: kubernetes-storage
