apiVersion: v1
kind: Pod
metadata:
  name: zeebe-worker
  labels:
    app: zeebe-worker
spec:
  restartPolicy: Always
  containers:
  - name: zeebe-worker
    image: josepht96/zeebe-worker:v2
    imagePullPolicy: Always
    resources: {}
    ports:
    - containerPort: 8080
    env:
    - name: ZEEBE_ADDRESS
      value: "camunda-zeebe-gateway.icamunda.svc.cluster.local:26500"
    - name: ZEEBE_HOST
      value: "camunda-zeebe-gateway.icamunda.svc.cluster.local"
    - name: ZEEBE_PORT
      value: "26500"
    # - name: ZEEBE_CLIENT_ID
    #   value: "zw"
    # - name: ZEEBE_CLIENT_SECRET
    #   value: "HNKuixezoxJHLH1KaBsOkQ7hbzeP0hb8"
    # - name: ZEEBE_AUTHORIZATION_SERVER_URL
    #   value: "http://camunda-keycloak.camunda.svc.cluster.local/auth/realms/camunda-platform/protocol/openid-connect/token"

