apiVersion: v1
kind: Pod
metadata:
  name: zeebe-worker
spec:
  restartPolicy: Always
  containers:
  - name: zeebe-worker
    image: josepht96/zeebe-worker:v1
    imagePullPolicy: Always
    resources: {}
    env:
    - name: ZEEBE_ADDRESS
      value: "camunda-zeebe-gateway.camunda.svc.cluster.local:26500"
    - name: ZEEBE_HOST
      value: "camunda-zeebe-gateway.camunda.svc.cluster.local"
    - name: ZEEBE_PORT
      value: "26500"
    - name: ZEEBE_CLIENT_ID
      value: "zw"
    - name: ZEEBE_CLIENT_SECRET
      value: "HNKuixezoxJHLH1KaBsOkQ7hbzeP0hb8"
    - name: ZEEBE_AUTHORIZATION_SERVER_URL
      value: "http://camunda-keycloak.camunda.svc.cluster.local/auth/realms/camunda-platform/protocol/openid-connect/token"


    # - name: ZEEBE_CLIENT_CONFIG_PATH
    #   value: /tmp/credentials
    # - name: ZEEBE_INSECURE_CONNECTION
    #   value: "true"
    # - name: ZEEBE_ADDRESS
    #   value: camunda-zeebe-gateway:26500
    # - name: ZEEBE_CLIENT_ID
    #   value: tasklist
    # - name: ZEEBE_CLIENT_SECRET
    #   valueFrom:
    #     secretKeyRef:
    #       key: tasklist-secret
    #       name: camunda-tasklist-identity-secret
    # - name: ZEEBE_AUTHORIZATION_SERVER_URL
    #   value: http://camunda-keycloak/auth/realms/camunda-platform/protocol/openid-connect/token