apiVersion: v1
kind: ConfigMap
metadata:
  name: postmanContent
data:
  exec.sh: |
{{ .Files.Get .Values.execFilePath | indent 4 }}
  environment.json: |
{{ .Files.Get .Values.envFilePath | indent 4 }}
  readOnlyTests.json: |
{{ .Files.Get .Values.readOnlyTestsFilePath | indent 4 }}
  writeTests.json: |
{{ .Files.Get .Values.writeTestsFilePath | indent 4 }}
