apiVersion: v1
kind: ReplicationController
metadata: 
  name: myapp-replicas
  labels:
    env: test
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        env: test
        type: pod
    spec:
      containers: 
        - name: nginx
          image: nginx
