apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    #these two values are assumed to be the same
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: myapp
  