apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  ports:
    #these two values are assumed to be the same
    - targetPort: 8080
      port: 8080
      nodePort: 30080
  selector:
    app: simple-webapp