execFilePath: files/exec.sh
envFilePath: files/env.postman_environment.json
readOnlyTestsFilePath: files/filetest.postman_collection.json
writeTestsFilePath: files/filetest-write.postman_collection.json
sleepPath: files/sleep.sh