apiVersion: v1
kind: Service
metadata:
  name: some-service
spec:
  type: NodePort
  ports:
    #these two values are assumed to be the same
    #make them the port the service is running on
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: you-app-name
  